### ISSUE TITLE
问下，你验证集上，acc可以大概达到多少

### ISSUE THREAD

**Issue by daixiangzi** [yizt/crnn.pytorch#14]

**Comment by yizt** [comment]
@daixiangzi 没有测试集哦，你希望在什么数据集上测试？

**Comment by daixiangzi** [comment]
没有呀，我说的验证集，是你在边训，边验证的过程中的精度



---原始邮件---
发件人: "mick.yi"<notifications@github.com&gt;
发送时间: 2020年6月21日(周日) 晚上9:17
收件人: "yizt/crnn.pytorch"<crnn.pytorch@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"daixiangzi"<543826458@qq.com&gt;;
主题: Re: [yizt/crnn.pytorch] 问下，你验证集上，acc可以大概达到多少 (#14)




 
@daixiangzi 没有测试集哦，你希望在什么数据集上测试？

**Comment by yizt** [comment]
@daixiangzi 之前没有做验证，加上了给你回复哈

**Comment by yizt** [comment]
@daixiangzi 你好，增加了评估，见readme, 水平方向精度0.893，垂直方向精度0.523
