### ISSUE TITLE
用自己的字典替换你的all_word.txt文件，训练报错

### ISSUE THREAD

**Issue by daixiangzi** [yizt/crnn.pytorch#15]
indices = np.array([self.alpha.index(c) for c in text])
ValueError: substring not found

**Comment by yizt** [comment]
@daixiangzi 这块之前逻辑是随机选择字体文件，然后从字体中随机选择字符；all_word.txt是全集；晚上修复一下这个问题，修复后给你消息哈。

**Comment by yizt** [comment]
@daixiangzi 已修复此问题

**Comment by daixiangzi** [comment]
> @daixiangzi 已修复此问题

ok,看到了，你demo.py里面的load_image处有一个bug，就是你没有考虑w=h的情况，我这边测试当图片尺寸为（75,75,1）的时候报错哟

**Comment by daixiangzi** [comment]
还有就是对于你生成部分代码有点疑问，就是你生成部分的逻辑是先固定背景图大小为32*512，然后再贴字上去，也就是固定尺寸的训练，但是你demo.py评估的时候仅仅只是把resize到了32，然后对w做同比例resize，我在想这是不是和训练不一致哇，难道不应该同样resize到32,512么

**Comment by yizt** [comment]
@daixiangzi 你好，训练时宽度必须固定；模型本身是识别不定长文本的，不是识别固定长度512；

**Comment by daixiangzi** [comment]
> @daixiangzi 你好，训练时宽度必须固定；模型本身是识别不定长文本的，不是识别固定长度512；
那识别的时候就只用把h压缩到32，就行吗

**Comment by yizt** [comment]
@daixiangzi 是的

**Comment by daixiangzi** [comment]
> @daixiangzi 是的



> @daixiangzi 是的



> @daixiangzi 是的

麻烦看看我刚说的错误哇，，

**Comment by daixiangzi** [comment]
> @daixiangzi 是的

麻烦看看我刚说的错误哇

**Comment by daixiangzi** [comment]
> @daixiangzi 是的

麻烦看看刚才的错误哇，输入为（75,75,1）的时候报错维度不匹配

**Comment by yizt** [comment]
@daixiangzi 特殊情况，没有考虑到，如果确定是水平或垂直方向，就直接用水平或垂直模型；不使用长度和宽度比例来判断；

**Comment by daixiangzi** [comment]
> @daixiangzi 特殊情况，没有考虑到，如果确定是水平或垂直方向，就直接用水平或垂直模型；不使用长度和宽度比例来判断；

ok，知道了，谢谢

**Comment by nissansz** [comment]
> @daixiangzi 已修复此问题

为什么我运行还是报这个错误？微信nlanguage

C:\Users\Ni\AppData\Local\Programs\Python\Python38\python.exe F:\Pycharm_Community_2020.2.4_Portable\plugins\python-ce\helpers\pydev\pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 57258 --file F:/pycharm2020.2/crnn.pytorch_generator/generator_LineSentence.py
pydev debugger: process 160356 is connecting

Connected to pydev debugger (build 202.8194.15)
嬖ㄕ袄肉论鋈佳②孟袭獍桷怙眚裴㈡睫伯钏奈萃曝
30
660
Traceback (most recent call last):
  File "F:\Pycharm_Community_2020.2.4_Portable\plugins\python-ce\helpers\pydev\pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "F:\Pycharm_Community_2020.2.4_Portable\plugins\python-ce\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/pycharm2020.2/crnn.pytorch_generator/generator_LineSentence.py", line 233, in <module>
    test_image_gen('horizontal')
  File "F:/pycharm2020.2/crnn.pytorch_generator/generator_LineSentence.py", line 213, in test_image_gen
    im, indices, target_len = gen.gen_image()
  File "F:/pycharm2020.2/crnn.pytorch_generator/generator_LineSentence.py", line 176, in gen_image
    indices = np.array([self.alpha.index(c) for c in text])
  File "F:/pycharm2020.2/crnn.pytorch_generator/generator_LineSentence.py", line 176, in <listcomp>
    indices = np.array([self.alpha.index(c) for c in text])
ValueError: substring not found

Process finished with exit code 1
