### ISSUE TITLE
如何使用自己的训练样本

### ISSUE THREAD

**Issue by wuhuanlin08** [yizt/crnn.pytorch#5]
你好，我有一批自己的训练集
image格式:
   demo_0.jpg
   样本_1.jpg
   ...

谢谢提供思路

**Comment by yizt** [comment]
@wuhuanlin08,你好，做好数据标注，新增一个自定义的Dataset读取自己的图像即可

**Comment by wuhuanlin08** [comment]
好的，我尝试你提供的思路，感谢回答
