### ISSUE TITLE
请问下，你data下面的三个txt字典文件有啥区别

### ISSUE THREAD

**Issue by daixiangzi** [yizt/crnn.pytorch#8]

**Comment by yizt** [comment]
@daixiangzi 您好，all_words.txt是fonts目录下所有字体文件中的字的并集；chinese_word.txt是all_words.txt中的中文字，simple_chinese_word.txt是chinese_word.txt中的简体中文字。

**Comment by daixiangzi** [comment]
没有单独的繁体字吗

---原始邮件---
发件人: "mick.yi"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 晚上6:44
收件人: "yizt/crnn.pytorch"<crnn.pytorch@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"daixiangzi"<543826458@qq.com&gt;;
主题: Re: [yizt/crnn.pytorch] 请问下，你data下面的三个txt字典文件有啥区别 (#8)




 
@daixiangzi 您好，all_words.txt是fonts目录下所有字体的字的并集；chinese_word.txt是all_words.txt中的中文字，simple_chinese_word.txt是chinese_word.txt中的简体中文字。

**Comment by yizt** [comment]
@daixiangzi 没有准备单独的繁体字;可以调用函数判断chinese_word.txt中的字是不是繁体字

**Comment by daixiangzi** [comment]
嗯嗯嗯

---原始邮件---
发件人: "mick.yi"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 晚上8:04
收件人: "yizt/crnn.pytorch"<crnn.pytorch@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"daixiangzi"<543826458@qq.com&gt;;
主题: Re: [yizt/crnn.pytorch] 请问下，你data下面的三个txt字典文件有啥区别 (#8)




 
@daixiangzi 没有准备单独的繁体字;可以调用函数判断chinese_word.txt中的字是不是繁体字

**Comment by daixiangzi** [comment]
还有这个函数的吗？方便能具体告诉一下吗

---原始邮件---
发件人: "mick.yi"<notifications@github.com&gt;
发送时间: 2020年5月28日(周四) 晚上8:04
收件人: "yizt/crnn.pytorch"<crnn.pytorch@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"daixiangzi"<543826458@qq.com&gt;;
主题: Re: [yizt/crnn.pytorch] 请问下，你data下面的三个txt字典文件有啥区别 (#8)




 
@daixiangzi 没有准备单独的繁体字;可以调用函数判断chinese_word.txt中的字是不是繁体字
