### ISSUE TITLE
请问有的字体绘制不出来是怎么解决的

### ISSUE THREAD

**Issue by daixiangzi** [yizt/crnn.pytorch#9]

**Comment by yizt** [comment]
@daixiangzi 增加相应字体的font文件；fonts目录下只包含了部分字体库

**Comment by daixiangzi** [comment]
> @daixiangzi 增加相应字体的font文件；fonts目录下只包含了部分字体库
还有一个问题，我看你默认；是加载的all_words.txt，根据你代码的里面的思路就是，首先统计了fonts下面每种字体的所有的char，利用字典对应起来，然后是从这里面随即选取。那么你这个all_words.txt，是不是你fonts下面所有字体，字符的并集去重的结果

**Comment by yizt** [comment]
@daixiangzi 是的，是字体的并集

**Comment by daixiangzi** [comment]
好的，谢谢
